### ISSUE TITLE
Optional Jupyter Notebook Kernel installation

### ISSUE THREAD

**Issue by villares** [hx2A/py5generator#13]
Hi, I'm following the step by step instructions and when I got into https://py5.ixora.io/install/#jupyter-notebook-kernel
I tried `python -m py5_tools.kernel.install --sys-prefix` and also with `sudo` but got errors.

```
Installing py5 Jupyter kernel spec
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/villares/.local/lib/python3.9/site-packages/py5_tools/kernel/install.py", line 89, in <module>
    main()
  File "/home/villares/.local/lib/python3.9/site-packages/py5_tools/kernel/install.py", line 85, in main
    install_py5_kernel_spec(user=args.user, prefix=args.prefix)
  File "/home/villares/.local/lib/python3.9/site-packages/py5_tools/kernel/install.py", line 54, in install_py5_kernel_spec
    KernelSpecManager().install_kernel_spec(
  File "/home/villares/.local/lib/python3.9/site-packages/jupyter_client/kernelspec.py", line 345, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/lib/python3.9/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.9/shutil.py", line 458, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter'
```
Thanks for having a look!

**Comment by villares** [comment]
I made a mistake, for some reason I must have changed terminals and the conda env was not active when I tried it!
WIth the p5coding env activated installation worked!

**Comment by hx2A** [comment]
Great! I am glad you got it working.

For anyone else reading this thread, note that py5 setup is simplest when using Anaconda.

Also, when installing the kernel, Jupyter needs to know where to install the kernel specifications to. In my opinion, it is a better idea to install kernels into the environment the kernel code is in. Otherwise, when you are using a different environment, Jupyter will present you the option to use kernels that won't actually work. It can get fairly messy and annoying.

That won't work for everyone though. To see what your options are, do this:

```
$ python -m py5_tools.kernel.install -h
usage: install.py [-h] [--user] [--sys-prefix] [--prefix PREFIX]

optional arguments:
  -h, --help       show this help message and exit
  --user           Install to the per-user kernels registry. Default if not root.
  --sys-prefix     Install to sys.prefix (e.g. a virtualenv or conda env)
  --prefix PREFIX  Install to the given prefix. Kernelspec will be installed in {PREFIX}/share/jupyter/kernels/
```
