### ISSUE TITLE
Running run_sketch.py on Windows

### ISSUE THREAD

**Issue by hx2A** [hx2A/py5generator#37]
### Discussed in https://github.com/hx2A/py5generator/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **tabreturn** August  9, 2021</sup>
I get an error running run_sketch.py on Windows. I enter something like: 

`py C:\Users\user\Desktop\thonny\env\Lib\site-packages\py5_tools\tools\run_sketch.py C:\Users\user\Desktop\a.py`

and I get --

```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\thonny\env\Lib\site-packages\py5_tools\tools\run_sketch.py", line 41, in <module>
    main()
  File "C:\Users\user\Desktop\thonny\env\Lib\site-packages\py5_tools\tools\run_sketch.py", line 37, in main
    imported.run_code(args.sketch_path, classpath=args.classpath)
  File "C:\Users\user\Desktop\thonny\env\lib\site-packages\py5_tools\imported.py", line 116, in run_code
    _run_static_code(
  File "C:\Users\user\Desktop\thonny\env\lib\site-packages\py5_tools\imported.py", line 140, in _run_static_code
    _run_code(new_sketch_path, classpath, new_process, exit_if_error)
  File "C:\Users\user\Desktop\thonny\env\lib\site-packages\py5_tools\imported.py", line 191, in _run_code
    _run_sketch(sketch_path, classpath, exit_if_error)
  File "C:\Users\user\Desktop\thonny\env\lib\site-packages\py5_tools\imported.py", line 162, in _run_sketch
    sketch_ast = ast.parse(sketch_code, filename=sketch_path, mode='exec')
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "C:\Users\user\AppData\Local\Temp\tmpx8li2fl7\_PY5_STATIC_FRAMEWORK_CODE_.py", line 12
    exec(
         ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

Something to do with Windows paths, maybe? Or I'm doing something silly? Any ideas?</div>

**Comment by hx2A** [comment]
> Or I'm doing something silly? Any ideas?

No, this is a silly bug. I thought I fixed all of instances of this problem already. The issue has to do with `C:\Users\user\Desktop\a.py` vs `C://Users//user//Desktop//a.py`. It should be an easy bug to fix.

**Comment by villares** [comment]
os.path.join() to the recue?

**Comment by hx2A** [comment]
@villares ha! Not this time. I am using `pathlib.Path` objects and need to use `.as_posix()` instead of directly converting it to a string. I thought I covered this already though...

**Comment by villares** [comment]
Oh `pathlib.Path` is the gold standard nowadays! :D

**Comment by hx2A** [comment]
Agreed! It works great, when used correctly!

**Comment by hx2A** [comment]
This is fixed and tested.
