### ISSUE TITLE
[OSX Apple Silicon] P2D and P3D renderer don't work

### ISSUE THREAD

**Issue by evayann** [hx2A/py5generator#76]
On my Mac Book Air M1 (2020), I run the following code :

```python
import py5_tools

py5_tools.add_options('-Dprocessing.natives.TestAppleSilicon=true')

import py5

def setup():
    py5.size(500, 500, py5.P2D)

def draw():
    py5.background(0.5)
    py5.circle(250, 250, py5.sin(py5.frame_count / 100) * 50)

py5.run_sketch()
```

When I running this program, I can see the sketch window appear and directly disappear. On terminal I have a `zsh trace trap`. With some search, this appear when exception isn't catch. More information [here](https://unix.stackexchange.com/a/21893). And this exception can be due to NSException like it said [here](https://stackoverflow.com/a/2613767).

If I don't use native Apple Silicon Lib to use Intel Lib instead. ie Remove line add_options ... . I have the following exception : 

```
java.lang.UnsatisfiedLinkError: Can't load library: /Users/yannzavattero/Documents/Projects/py5/natives/macosx-universal/gluegen_rt
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
        at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
        at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
        at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
        at com.jogamp.common.os.Platform$1.run(Platform.java:321)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
        at com.jogamp.nativewindow.NativeWindowFactory$1.run(NativeWindowFactory.java:239)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:236)
        at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
        at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:475)
        at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:147)
        at processing.core.PApplet.initSurface(PApplet.java:10480)
        at processing.core.PApplet.runSketch(PApplet.java:10386)
        at org.jpype.proxy.JPypeProxy.hostInvoke(Native Method)
        at org.jpype.proxy.JPypeProxy.invoke(Unknown Source)
        at jdk.proxy2/jdk.proxy2.$Proxy8.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by hx2A** [comment]
Thank you for working with me on this. There are a couple of things that surprise me here.

```text
java.lang.UnsatisfiedLinkError: Can't load library: /Users/yannzavattero/Documents/Projects/py5/natives/macosx-universal/gluegen_rt
```

Seeing `universal` is unexpected. After poking around in the Processing source code, I learned that there are such things are ["universal" libraries](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary) for OSX machines.

Can you show me the full output of this command on your machine?

```zsh
java -XshowSettings:properties -version
```

I'm particularly interested in the value of `os.arch`.

The [relevant py5 code is here](https://github.com/hx2A/py5generator/blob/ac731f9dca94a9c2a2bc06bc4f4178dc12b2ad36/py5_jar/src/main/java/py5/core/Sketch.java#L71). It is the only place where `processing.natives.TestAppleSilicon` does anything.

Here's what confuses me: if `System.getProperty("os.arch")` is equal to `"universal"`, then wouldn't the `if` statement on line 72 always be false, regardless of what `processing.natives.TestAppleSilicon` is set to? If so, wouldn't your results be same when that `add_options` line is used or not used? Is something changing `System.getProperty("os.arch")` from `"aarch64"` to `"universal"` Somewhere? I don't see anything like that in the Processing code.

Can you try recreating that `UnsatisfiedLinkError` exception and then run this python code:

```python
import jpype

System = jpype.JClass("java.lang.System")
print(System.getProperty("os.arch"))
```

If something is changing it, this will show it.

**Comment by hx2A** [comment]
Another thing I will ask you to try is this:

```python
import py5_tools

py5_tools.add_options('-Dos.arch=x86_64')

import py5

def setup():
    py5.size(500, 500, py5.P2D)

def draw():
    py5.background(0.5)
    py5.circle(250, 250, py5.sin(py5.frame_count / 100) * 50)

py5.run_sketch()
```

**Comment by hx2A** [comment]
Can you try this:

```python
import py5

System = jpype.JClass("java.lang.System")
print(System.getProperty("os.arch"))

def setup():
    py5.size(500, 500, py5.P2D)

def draw():
    py5.background(0.5)
    py5.circle(250, 250, py5.sin(py5.frame_count / 100) * 50)

py5.run_sketch()
```

Then after you get the UnsatisfiedLinkError, do this again:

```python
print(System.getProperty("os.arch"))
```

My guess is it will be `aarch64` the first time and `universal` the second time.

**Comment by evayann** [comment]
I don't succeed to make a `print(System.getProperty("os.arch"))` when UnsatisfiedLinkError is trigger.
But first time, the value is `aarch64`

**Comment by hx2A** [comment]
> I don't succeed to make a `print(System.getProperty("os.arch"))` again when UnsatisfiedLinkError is trigger. But first time, the value is `aarch64`

Why? Is Python crashing and preventing you from doing that?

Try this instead:

```python
import py5
from java.lang import System
print(System.getProperty("os.arch"))
print(System.getProperty("java.library.path"))
```

This is helpful.

**Comment by evayann** [comment]
Python don't continue execution and still lock on UnstatisfiedLinkError.
```
aarch64
java.lang.UnsatisfiedLinkError: Can't load library: /Users/yannzavattero/Documents/Projects/py5/natives/macosx-universal/gluegen_rt
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
        at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
        at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
        at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
        at com.jogamp.common.os.Platform$1.run(Platform.java:321)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
        at com.jogamp.nativewindow.NativeWindowFactory$1.run(NativeWindowFactory.java:239)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:236)
        at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
        at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:475)
        at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:147)
        at processing.core.PApplet.initSurface(PApplet.java:10480)
        at processing.core.PApplet.runSketch(PApplet.java:10386)
        at org.jpype.proxy.JPypeProxy.hostInvoke(Native Method)
        at org.jpype.proxy.JPypeProxy.invoke(Unknown Source)
        at jdk.proxy2/jdk.proxy2.$Proxy8.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

For the following code 

```
import py5
from java.lang import System
print(System.getProperty("os.arch"))
print(System.getProperty("java.library.path"))
```

I have the output 

```
aarch64
/Users/yannzavattero/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.:/opt/homebrew/lib/python3.9/site-packages/py5/natives/macos-x86_64
```

**Comment by hx2A** [comment]
Aha! I think I see what is going on.

From your earlier message 2 hours ago, you have

```text
    java.library.path = /Users/yannzavattero/Library/Java/Extensions
        /Library/Java/Extensions
        /Network/Library/Java/Extensions
        /System/Library/Java/Extensions
        /usr/lib/java
        .
```
When you import py5, py5 is correctly adding `/opt/homebrew/lib/python3.9/site-packages/py5/natives/macos-x86_64` to the end. However, Processing is trying to load the library from `/Users/yannzavattero/Documents/Projects/py5/natives/macosx-universal/`, which is a subdirectory of the current working directory the py5_test.py file is in. The `.` in your java.library.path is in front of what py5 is adding to the path. Maybe if that is removed it will stop looking in the current directory? Can you try this:

```python
import py5

from java.lang import System

# remove . from java.library.path
System.setProperty("java.library.path", "/Users/yannzavattero/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:/opt/homebrew/lib/python3.9/site-packages/py5/natives/macos-x86_64")

def setup():
    py5.size(500, 500, py5.P2D)

def draw():
    py5.background(0.5)
    py5.circle(250, 250, py5.sin(py5.frame_count / 100) * 50)

py5.run_sketch()
```

If that doesn't work and you still get the same exact error, can you try copying the contents of `/opt/homebrew/lib/python3.9/site-packages/py5/natives/macos-x86_64/` to a new directory `/Users/yannzavattero/Documents/Projects/py5/natives/macosx-universal/`? This will at least tell us if it will work if it can find the native libraries.

**Comment by evayann** [comment]
The code snippet don't work sorry...
I copy the content of the repertory like this : 
<img width="865" alt="Capture d’écran 2022-04-06 à 23 30 39" src="https://user-images.githubusercontent.com/37276188/162074918-e38145bc-1aea-45b7-982f-908c45f774d7.png">
And isn't better...

Still don't find the lib...

```
java.lang.UnsatisfiedLinkError: Can't load library: /Users/yannzavattero/Documents/Projects/py5/natives/macosx-universal/gluegen_rt
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
        at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
        at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
        at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
        at com.jogamp.common.os.Platform$1.run(Platform.java:321)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
        at com.jogamp.nativewindow.NativeWindowFactory$1.run(NativeWindowFactory.java:239)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:236)
        at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
        at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:475)
        at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:147)
        at processing.core.PApplet.initSurface(PApplet.java:10480)
        at processing.core.PApplet.runSketch(PApplet.java:10386)
        at org.jpype.proxy.JPypeProxy.hostInvoke(Native Method)
        at org.jpype.proxy.JPypeProxy.invoke(Unknown Source)
        at jdk.proxy2/jdk.proxy2.$Proxy8.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by hx2A** [comment]
Hmmmm. I'm running out of ideas.

If you haven't done so already, can you download and install the Processing IDE from https://processing.org/download for Macs, and then run this simple Sketch through Processing:

```java
size(200, 200, P2D);

println(System.getProperty("java.library.path"));
```
In the output you might see a directory name with `macosx-universal` in it. If so, can you tell me the contents of that directory?

**Comment by evayann** [comment]
I have already installed processing. The result of 

```
size(200, 200, P2D);

println(System.getProperty("java.library.path"));
```

is 

`:/Applications/Processing.app/Contents/Java/core/library/macos-x86_64:/Applications/Processing.app/Contents/MacOS`

When I open the repository of macOS-x86_64, I have this element (same as in py5). 

<img width="626" alt="image" src="https://user-images.githubusercontent.com/37276188/162126334-75aea237-46c7-4e0c-8802-2044a15664de.png">

I try to copy past the content of this repo in my natives, macosx-universal but isn't better...

**Comment by hx2A** [comment]
Have you installed Rosetta on your machine? I've done some research and it doesn't seem like it is installed by default.

Can you try running Sketches through Jupyter notebook instead of the generic Python interpreter? On OSX, if a Sketch is run through the generic Python interpreter, closing the Sketch will kill the Python process. This prevents any analysis of the situation after the Sketch is launched or an exception is thrown. However, if a Sketch is run through a Jupyter notebook, you can execute other cells while the Sketch is running or after it dies.

What you can do is run this series of notebook cells, one at a time:

```ipython
%gui osx
```

then

```ipython
import py5

from java.lang import System
print(System.getProperty("os.arch"))
print(System.getProperty("java.library.path"))
```

then run the Sketch

```ipython
def setup():
    py5.size(500, 500, py5.P2D)

def draw():
    py5.background(0.5)
    py5.circle(250, 250, py5.sin(py5.frame_count / 100) * 50)

py5.run_sketch()
```

while the Sketch is running, or after the exception is thrown, do this again:

```ipython
print(System.getProperty("os.arch"))
print(System.getProperty("java.library.path"))
```

I'm convinced `os.arch` will change from `aarch64` to `universal`.

The second problem is that OSX has this thing called "universal binaries" that can be created with the `lipo` terminal command. The exception is being thrown because Processing is looking for these universal binaries but they are simply not on your machine anywhere. I'm not sure where they are supposed to come from.

https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by hx2A** [comment]
I've been experimenting with pyinstaller and writing documentation for how package a py5 Sketch. My documentation works well Linux but does not work for OSX. When I run a packaged Sketch that uses the P2D renderer, I get this exception:

```
java.lang.UnsatisfiedLinkError: Can't load library: /private/tmp/test/dist/simple/natives/macosx-universal/nativewindow_awt
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at jogamp.nativewindow.NWJNILibLoader.access$000(NWJNILibLoader.java:39)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:49)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:41)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at jogamp.nativewindow.NWJNILibLoader.loadNativeWindow(NWJNILibLoader.java:41)
	at jogamp.nativewindow.jawt.JAWTUtil.<clinit>(JAWTUtil.java:345)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.jogamp.nativewindow.NativeWindowFactory$2.run(NativeWindowFactory.java:405)
	at com.jogamp.nativewindow.NativeWindowFactory$2.run(NativeWindowFactory.java:401)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:401)
	at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
	at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:475)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:147)
	at processing.core.PApplet.initSurface(PApplet.java:10480)
	at processing.core.PApplet.runSketch(PApplet.java:10386)
	at org.jpype.proxy.JPypeProxy.hostInvoke(Native Method)
	at org.jpype.proxy.JPypeProxy.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy8.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Observe it can't find a `macosx-universal` library. This is on my non-Apple Silicon machine. Confusing, but perhaps it will give me a chance to understand where `universal` is coming from.

**Comment by hx2A** [comment]
py5 version 0.6.0 worked fine on Apple Silicon and I believe 0.7.0 worked also. The Processing team started making changes to use native opengl libraries on Apple Silicon, and those efforts are a work in progress. I need to understand what those changes are to repair py5 on that hardware.

**Comment by hx2A** [comment]
The P2D and P3D renderers now work on Apple Silicon, as per tests done in issue #87. The error message in #87 will be resolved in the next release.
